### PR TITLE
Water pump and offshore pump fixes and updates to 0.16

### PR DESCRIPTION
**Pull request by D10X1D0**
before, 1  input, 1 output  the input does not pass fluid  or connect to other pipes
http://steamcommunity.com/sharedfiles/filedetails/?id=1263653207
after just the 1 water output
http://steamcommunity.com/sharedfiles/filedetails/?id=1263653372

### CODE REVIEW

**Comment by D10X1D0** [comment]
TL;DR
updated offshore pumps to the new 0.16 standard 

http://steamcommunity.com/sharedfiles/filedetails/?id=1264396713

Updated water pump "oil driller" to remove it's input fluidbox since it just outputs from one side.

**Comment by D10X1D0** [comment]
Added fast-replace group offshore-pump to the vanilla and modded offshore pumps. 
They can be replaced now.

**Comment by D10X1D0** [comment]
factorio 0.16.16
Duplicate wire-connection definition clean up on offshore pumps.
Connections On/Off
http://steamcommunity.com/sharedfiles/filedetails/?id=1267655034
http://steamcommunity.com/sharedfiles/filedetails/?id=1267654916

**Comment by McGuten** [comment]
Thanks you so much guy ^^

**Pull request merged**
